targets:
  $default:
    builders:
      assets_indexer|assets_indexer:
        enabled: True

additional_public_assets:
  - ./../

builders:
  assets_indexer:
    import: 'package:assets_indexer/assets_indexer.dart'
    builder_factories: ['assetsIndexer']
    build_extensions:
      .jpg:
        - .assets.dart
      .png:
        - .assets.dart
      .webp:
        - .assets.dart
      .gif:
        - .assets.dart
        - .assets.dart
      .yaml:
        - .assets.dart
    auto_apply: dependents
    build_to: source