targets:
  $default:
    builders:
      assets_indexer|assetsIndexer:
        enabled: True

additional_public_assets:
  - ./../

builders:
  assetsIndexer:
    import: 'package:assets_indexer/assets_indexer.dart'
    builder_factories: ['assetsIndexer']
    build_extensions:
      .jpg:
        - .asset.dart
      .png:
        - .asset.dart
      .webp:
        - .asset.dart
      .gif:
        - .asset.dart
    auto_apply: dependents
    build_to: source
  fontFamiliesIndexer:
    import: 'package:assets_indexer/assets_indexer.dart'
    builder_factories: ['fontFamiliesIndexer']
    build_extensions:
      .yaml:
        - .asset.dart
      .ttf:
        - .asset.dart
      .otf:
        - .asset.dart
    auto_apply: dependents
    build_to: source