name: assets_indexer
description: To generate indexed constants for your assets in dart/flutter project! Inspired by android R.java concept
version: 0.0.3
homepage: https://github.com/ishaquehassan/assets_indexer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: any
  path: ^1.8.0
  mustache: ^1.1.1
  quartet: ^0.1.1
  numbers_to_words: ^0.1.2 
 
dev_dependencies:
  build_config: any
  build_runner: any