name: assets_generator
description: A new Flutter package project.
version: 0.0.1
author: Ishaq Hassan
homepage: https://github.com/ishaquehassan/assets_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^2.0.1
  path: ^1.8.0
  mustache: ^1.1.1
  quartet: ^0.1.1
 
dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.0.2